spring:
  application:
    name: transport-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/transport_db
    username: admin_transport
    password: CrossYourFit753#
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    defer-datasource-initialization: true

  flyway:
    enabled: false

  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    time-zone: Africa/Kinshasa

  resend:
    api-key: ${RESEND_API_KEY:re_ZKPuAKS8_AozT9S8PvFiyiFXJDwnF9MXQ}
    from-email: ${RESEND_FROM_EMAIL:noreply@transport-rdc.com}
    base-url: https://api.resend.com

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  refresh-expiration: 604800000

reservation:
  verrouillage:
    timeout-minutes: 15

logging:
  level:
    com.transport: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always